import Navbar from './components/navbar/Navbar'

import { PT_Sans } from 'next/font/google' 

import './globals.css'

export const metadata = {
  title: 'Giggity',
  description: 'Generated by create next app',
}

const font = PT_Sans({
  subsets: ['latin'],
  weight: '400'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
